### ISSUE TITLE
UI tweak for `Save Workout` page

### ISSUE THREAD

**Issue by ckelwin** [EXERLOG/exer_log#27]
Problem:
The `textfield` on this page is the `template name`. The textfield is enabled even when the checkbox for `Save as template` is disabled. This may cause confusion to some, as the `hintText` for the textfield even says `name your workout`.

Suggestion:
1. Move the textfield down, after the checkbox. Textfield should be disabled when checkbox is unchecked, and enabled when checked.
2. Update the hinttext to something like `template name` or `name of template`.

![image](https://user-images.githubusercontent.com/5429312/183302469-f9e319cd-ec4d-4fe6-b777-caf4d5d28408.png)

**Comment by KalleHallden** [comment]
Yeah I'm not sure if this is the best way to do it but my thinking has been that it might be good to allow the user to name their workout even if they don't save it as a template. I don't know if I've thought this through though so it might be that there is never a case where a user will want to see the name of an old workout but not have it saved as a template. So it might be better the way that you suggest but I'm not sure. What do you think?
