### ISSUE TITLE
Fix navigation

### ISSUE THREAD

**Issue by jorre127** [EXERLOG/exer_log#41]
When finishing a workout you go to the calendar page. But the problem is that you can then navigate back using the back arrow to the workout you just finished (I assume this is not intended seeing as we already finished and saved this workout at this moment). 

Also when pressing the back button on the workout page, we do a pop and then push to the calendar screen. This looks visually confusing because we press back, but it looks like a new page gets pushed onto the screen.

My suggestion is to change the navigation flow so when you go from the calendar page to the workout page we do this with a push instead ( its a push replace now) this way we can just pop when pressing the back button. Same for when we save the session we can just pop back to the calendar page. This way we don't have the problem where we can navigate back to a already finished session.

https://user-images.githubusercontent.com/44479965/184024924-fb3f3727-8402-410a-9991-1a354e495c64.mp4

**Comment by jorre127** [comment]
Also fix this issue where we can go back twice when opening a workout from the calendar

https://user-images.githubusercontent.com/44479965/184025582-ccd8b867-eec8-4a2d-ad29-98270eade537.mp4

**Comment by ramsy0dev** [comment]
i think i did fix this in #99
