### ISSUE TITLE
Block ability to enter empty workout name

### ISSUE THREAD

**Issue by jorre127** [EXERLOG/exer_log#42]
Now there is no check to see if you entered an empty workout name. This might cause some issue later on. Also check on duplicate workout names. The dropdown button expects every dropdown menu item to have a unique value, so it break when you have multiple items of the same value. This is how it looks when I added multiple workouts with no name.
<img width="463" alt="Screenshot 2022-08-10 at 23 50 37" src="https://user-images.githubusercontent.com/44479965/184026729-ad5e1636-1d60-4657-8989-38156d05d390.png">

**Comment by KalleHallden** [comment]
Yeah that is a good point. Duplicate workout names need to be checked for. My thinking about empty workout names was just that the naming of a workout is only for when you want to save the workout as a template to redo later. So maybe not the best UX but the idea was, if the workout name is left blank then it isn't a workout template so then it doesn't matter and should be blank. But like you've shown it also means that a user can save a workout template with no name. Which shouldn't be possible.

**Comment by KalleHallden** [comment]
@all-contributors please add @jorre127 for bug reports and reviewed pull requests
