### ISSUE TITLE
Exercise totals widget not working when viewing workout from calendar

### ISSUE THREAD

**Issue by jorre127** [EXERLOG/exer_log#46]
The exercise totals widget seems to always display 0 when opening a workout from the calendar in view mode, in redo mode it seems to work fine.
![Screenshot 2022-08-11 at 23 14 39](https://user-images.githubusercontent.com/44479965/184243442-d459b64b-71a3-416c-9893-7430a9f38afd.png)

**Comment by KalleHallden** [comment]
Yeah it should work but it doesn't auto update as the reps and stuff change. It's a button, so you can press it and then it will update the numbers correctly. Not very well written, this was one of the smaller bugs that I had forgotten about hehe

**Comment by ramsy0dev** [comment]
can we save the total for each workout in the firestore then when viewing the workout it will display that total instead of recalculating eveything ?

**Comment by mfederowicz** [comment]
maybe the problem is with implementation because when you click REDO button:

```
onPressed: () {
        Navigator.pop(context);
        Navigator.of(context).pop();
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => WorkoutPage(widget.workout),
          ),
        );
      },
```
totals widget works well, and each button click shows proper values, but VIEW button have:

```
onPressed: () {
        addExercises(widget.workout);
        Navigator.pop(context);
      },
```
Iam just guesting, because for now my application flow knowledge is on beginning level :)
