### ISSUE TITLE
Fix move function body out of the widgets

### ISSUE THREAD

**Issue by richardamare** [EXERLOG/exer_log#60]
It would be much better if there would be a function (`void doSomething() { ... }`) instead of leaving a function logic inside of a widget

```dart
// Instead of:

TextButton(
    child: const Text("Click Me"),
    onPressed: () { ... },
)

// Do:

// somewhere in the widget scope..
void doSomething() { ... }

// Widget body
TextButton(
    child: const Text("Click Me"),
    onPressed: doSomething,
)
```

**Comment by KalleHallden** [comment]
Yeah good idea

**Comment by ShivamMenda** [comment]
Hey, @KalleHallden Can I take up this issue if it's up for grabs?  
It would help me understand the codebase better for future contributions.

**Comment by KalleHallden** [comment]
@ShivamMenda yes absolutely! Thank you

**Comment by ShivamMenda** [comment]
@KalleHallden I'll look into it thanks! While Creating the PR I'll also mention the file names and functions I changed so that it'll be easy to check and keep track.
