### ISSUE TITLE
login and forgot password feedback for users valid with OWASP recommedations

### ISSUE THREAD

**Issue by mfederowicz** [EXERLOG/exer_log#64]
Hi @KalleHallden I know that login feedback for users were raised in that [PR](https://github.com/KalleHallden/exer_log/pull/16)
but for seucrity reasons i think will be good to use OWASP recommendations for that kind of labels (ie: dont inform user that used credentials match/dont match to existing accout)

source of correct and incorrect responses

1. https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html
2. https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#incorrect-and-correct-response-examples

**Comment by suzanpradhan** [comment]
Great. I guess we can change Login error responses to "Login failed; Invalid email or password."

But for Account Creation,

![image](https://user-images.githubusercontent.com/74817169/184575093-d1e690da-b280-435c-ab74-d50ab166ed6b.png)

As of now, we dont have any verification email sent to user mail, so do we have any suggestion for that?

**Comment by mfederowicz** [comment]
Hmm, it is not good to give users access to system without veryfication of email account. I know that application is in early development stage, but maybe it is good point to think about it :)

**Comment by KalleHallden** [comment]
Yeah I think this is a good thing to correct as well.

**Comment by KalleHallden** [comment]
@all-contributors please add @suzanpradhan for project management and ideas & planning
