### ISSUE TITLE
Generic Error Screen & Error Widgets

### ISSUE THREAD

**Issue by dinurymomshad** [EXERLOG/exer_log#69]
For any unexpected issue, we can show the Generic Error Screen. We can also add some generic error widgets.

**Comment by KalleHallden** [comment]
@all-contributors please add @dinurymomshad for architecture and code

**Comment by jorre127** [comment]
@KalleHallden I don't know If this would be too much work, but maybe for issues like this were new UI items are being added it would be good if you provided a design? This way the app stays uniform design-wise and we don't get a bunch of mismatched widgets designed by different people.

**Comment by KalleHallden** [comment]
@jorre127 yeah that is a good idea. Is there a convention for how to add design suggestions or do I just attach images in issue comments?

**Comment by jorre127** [comment]
@KalleHallden I don't know what programme you use to design, but if you were using Figma you can just add links to the pages here, this way we can see the exact measurements, colours etc. I'm sure other design platforms have something similar.

**Comment by KalleHallden** [comment]
Okay I'll take a look at that then, I used adobe xd to design it

**Comment by momshaddinury** [comment]
@KalleHallden I'd suggest Figma because it lets you share links to specific screens. And it's a web app so easier to view.

**Comment by KalleHallden** [comment]
Yeah I've done some googling and figma seems to be the best candidate
